version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0
    container_name: oracle-xe
    environment:
      - ORACLE_PWD=Bayonetta2024
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./src/main/resources/wallet:/opt/oracle/oradata/network/admin # Montamos el wallet
    healthcheck:
      test: ["CMD", "ls", "/opt/oracle/oradata"]
      interval: 30s
      timeout: 10s
      retries: 10

  usuarioback:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usuarioback-service
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
